version: '2'
services:
  zookeeper:
    container_name: aip-zookeeper
    restart: unless-stopped
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:2181:2181"
  kafka:
    container_name: aip-kafka
    restart: unless-stopped
    build: .
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: aip-kafka
      KAFKA_ZOOKEEPER_CONNECT: aip-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    external:
      name: localnet
